apiVersion: v1
kind: Pod
metadata:
  name: enclave-manager
  labels:
    app: tee
spec:
  containers:
  - image: sammyne/hyperledger-tcf
    name: enclave-manager
    command: ["/bin/bash"]
    args: ["$(TCF_HOME)/scripts/enclave_manager.sh"]
    env:
    - name: TCF_HOME
      value: /project/TrustedComputeFramework