apiVersion: v1
kind: Pod
metadata:
  name: lmdb
  labels:
    app: database
spec:
  containers:
  - image: sammyne/hyperledger-tcf
    name: lmdb-server
    command: ["/bin/bash"]
    args: ["$(TCF_HOME)/scripts/lmdb.sh"]
    env:
    - name: TCF_HOME
      value: /project/TrustedComputeFramework
    ports:
    - containerPort: 9090
      protocol: TCP
    volumeMounts:
    - name: db
      mountPath: /lmdb
  volumes:
  - name: db
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lmdb
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: database